parameters :
    app_name : "Tada.io"

    root_dir : /welean3-tada/app
    view_dir : /welean3-tada/app/browser/phtml
    secured_dir: /welean3-tada/tmp
    production_mode: false

    root_url: http://www.local.tada.io

    cookie :
        domain : .local.tada.io

    default_locale:
        default: fr

    db :
        adapter : PDO_PGSQL
        params :
            host : 10.12.20.133
            port : 5432
            username : postgres
            password : postgres
            dbname : tada

    memcached :
        host : 127.0.0.1
        port : 11211

    notification :
        host : http://127.0.0.1
        port : 3001
        uri : /notification