<div class="container">

    <?php echo $this->getResult('header'); ?>
    <div class='content'>
        <div class='breadcrumb'>
            <a href="#" class="bc-item">Home</a>
            <a href="#" class="bc-item">Evaneos</a>
            <a href="#" class="bc-item">PRO</a>
        </div>
        <div class='levels'></div>

    </div>

</div>
<?php echo $this->getResult('task'); ?>
<?php echo $this->getResult('template'); ?>
