
<script id="level1" type="text/x-handlebars-template">
    <h1 id="tada-{{id}}" class="{{level}} parent-id-{{parent_id}}">{{title}}</h1>
</script>
<script id="level2" type="text/x-handlebars-template">
    <div class='{{level}} parent-id-{{parent_id}}'>
        <div id="tada-{{id}}" class="task {{#ifel children}}plus{{/ifel}}">
            <span class='title'>{{title}}</span>
            <span class='description'>{{description}}</span>
        </div>
    </div>
</script>