<!DOCTYPE html>
<html>
    <head>
    <title>Tada.io</title>
        <link rel="stylesheet" type="text/css" href="css/style.css">
    </head>

    <body>
        <?php echo $this->getResult(); ?>
    </body>

    <script type="text/javascript">
        var SOCKET_HOST = "<?php echo $this->socketUrl; ?>";
    </script>


    <script src="<?php echo $this->socketUrl; ?>/socket.io/socket.io.js" type="text/javascript"></script>
    <script src="js/jquery-2.1.1.min.js" type="text/javascript"></script>
    <script src="js/handlebars-v2.0.0.js" type="text/javascript"></script>
    <script src="js/app.js" type="text/javascript"></script>

</html>