

<!DOCTYPE html>
<html>
<head>
<title>Tada.io</title>

    <link rel="stylesheet" type="text/css" href="css/style.css">
    <script src="js/jquery-2.1.1.min.js" type="text/javascript"></script>
    <script src="js/handlebars-v2.0.0.js" type="text/javascript"></script>
    <script src="js/app.js" type="text/javascript"></script>

</head>
<body>
    <?php echo $this->getResult(); ?>
</body>

</html>