<!DOCTYPE html>
<html ng-app="tada">
    <head>
    <title>Tada.io</title>
        <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="/css/lib.css">
        <link rel="stylesheet" type="text/css" href="/css/style.css">
    </head>

    <body>
        <?php echo $this->getResult(); ?>
    </body>
    <script src="/js/app.js" type="text/javascript"></script>


</head>

</html>