classes :
    IndexController :
        class : \Tada\Controller\IndexController
        props :
            socketUrl : %socket_url

    GetAllController :
        class : \Tada\Controller\GetAllController
        call :
            setTaskService : [ @Berthe-tasks-Service ]

    UpdateTaskController :
        class : \Tada\Controller\UpdateTaskController
        call :
            setTaskService : [ @Berthe-tasks-Service ]

    CreateTaskController :
        class : \Tada\Controller\CreateTaskController
        call :
            setTaskService : [ @Berthe-tasks-Service ]

    TaskBreadcrumbController :
        class : \Tada\Controller\TaskBreadcrumbController
        call :
            setTaskService : [ @Berthe-tasks-Service ]
            setBuilder : [ @Berthe-tasks-RESTBuilder ]
            setSerializer : [ @EmbedSerializer ]
