classes :
    CreatedDateSaveHook :
        class : \Tada\Hook\CreatedDateSaveHook
    UpdatedDateSaveHook :
        class : \Tada\Hook\UpdatedDateSaveHook
    NotificationSaveHook :
        class : \Tada\Hook\NotificationSaveHook
        arguments : [ @NotificationService ]
    UpdateAllRankSaveHook :
        class : \Tada\Hook\UpdateAllRankSaveHook
        arguments : [ @Berthe-tasks-Manager ]