parameters :
    crud :
        packages :
            tasks : { 'vo' : '\Tada\Model\Task', 'rest' : '\Tada\REST\TaskREST', 'table' : 'task' }
            tags : { 'vo' : '\Tada\Model\Tag', 'rest' : '\Tada\REST\TagREST', 'table' : 'tag' }
            tagcategories : { 'vo' : '\Tada\Model\TagCategory', 'rest' : '\Tada\REST\TagCategoryREST', 'table' : 'tag_category' }
            taskhastags : { 'vo' : '\Tada\Model\TaskHasTag', 'rest' : '\Tada\REST\TaskHasTagREST', 'table' : 'task_has_tag' }

classes :
    Berthe-tasks-RESTBuilder :
        class : \Tada\RESTBuilder\TaskRESTBuilder
        call :
            setContainer : [ $container ]
            setResourceName : [ 'tasks' ]
            setService : [ @Berthe-tasks-Service ]
            setTagService : [ @Berthe-tags-Service ]
            setTaskHasTagService : [ @Berthe-taskhastags-Service ]

    Berthe-tasks-FetcherBuilder:
        class : \Tada\FetcherBuilder\TaskFetcherBuilder

    Berthe-tags-FetcherBuilder:
        class : \Tada\FetcherBuilder\TagFetcherBuilder

    Berthe-tags-RESTBuilder :
        class : \Tada\RESTBuilder\TagRESTBuilder
        call :
            setContainer : [ $container ]
            setResourceName : [ 'tags' ]
            setTagCategoryService : [ @Berthe-tagcategories-Service ]

    Berthe-tagcategories-RESTBuilder :
        class : \Tada\RESTBuilder\TagCategoryRESTBuilder
        call :
            setContainer : [ $container ]
            setResourceName : [ 'tagcategories' ]

    Berthe-tags-Fetcher :
        class: \Tada\Fetcher\TagFetcher

    Berthe-tasks-Manager :
        class : \Tada\Manager\TaskManager
        singleton : true
        call :
            addSaveHook[0] : [ @CreatedDateSaveHook ]
            addSaveHook[1] : [ @UpdatedDateSaveHook ]
            addSaveHook[2] : [ @UpdateAllRankSaveHook ]
            addSaveHook[3] : [ @NotificationSaveHook ]
            setValidator : [ @Berthe-tasks-Validator ]
            setStorage : [ @Berthe-tasks-Storage ]
            setVOFQCN : [ '\Tada\Model\Task' ]

    Berthe-taskhastags-Manager :
        class : \Berthe\BaseManager
        call :
            addSaveHook[0] : [ @CreatedDateSaveHook ]
            setValidator : [ @Berthe-taskhastags-Validator ]
            setStorage : [ @Berthe-taskhastags-Storage ]
            setVOFQCN : [ '\Tada\Model\TaskHasTag' ]

    Berthe-taskhastags-Service :
        class: \Berthe\BaseService
        arguments: [ @Berthe-taskhastags-Manager, @Berthe-taskhastags-Builder ]

    Berthe-tasks-Storage :
        class : \Tada\Storage\TaskStorage
        call :
            addStore[0] : [ @Berthe-tasks-PersistentStore ]

    Berthe-tasks-PersistentStore :
        class : \Tada\PersistentStore\TaskPersistentStore
        call :
            setReader : [ @Berthe-tasks-Reader ]
            setWriter : [ @Berthe-tasks-Writer ]

    Berthe-tasks-Writer :
        class : \Tada\Writer\TaskWriter
        call :
            setDb : [ @DbWriter ]
            setTableName : [ 'task' ]

    Berthe-tasks-Builder :
        class : \Tada\Builder\TaskBuilder

    Berthe-taskhastags-Builder :
        class : \Tada\Model\TaskHasTagBuilder

    Berthe-tasks-Service :
        class: \Tada\Service\TaskService
        arguments: [ @Berthe-tasks-Manager, @Berthe-tasks-Builder ]
        call:
            setTagService: [ @Berthe-tags-Service ]
            setTagCategoryService: [ @Berthe-tagcategories-Service ]
            setTaskHasTagService: [ @Berthe-taskhastags-Service ]

    Berthe-tagcategories-Service :
        class: \Tada\Service\TagCategoryService
        arguments: [ @Berthe-tagcategories-Manager, @Berthe-tagcategories-Builder ]

    Berthe-tags-Service :
        class: \Tada\Service\TagService
        arguments: [ @Berthe-tags-Manager, @Berthe-tags-Builder ]
        call:
            setTagCategoryService: [ @Berthe-tagcategories-Service ]

