parameters :
    crud :
        packages :
            tasks : { 'vo' : '\Tada\Model\Task', 'rest' : '\Tada\REST\TaskREST', 'table' : 'task' }


classes :
    Berthe-tasks-RESTBuilder :
        class : \Tada\RESTBuilder\TaskRESTBuilder
        call :
            setContainer : [ $container ]
            setResourceName : [ 'tasks' ]
    Berthe-tasks-FetcherBuilder:
        class : \Tada\FetcherBuilder\TaskFetcherBuilder