parameters :
    crud :
        packages :
            tasks : { 'vo' : '\Tada\Model\Task', 'rest' : '\Tada\REST\TaskREST', 'table' : 'task' }
            tags : { 'vo' : '\Tada\Model\Tag', 'rest' : '\Tada\REST\TagREST', 'table' : 'tag' }
            tagcategories : { 'vo' : '\Tada\Model\TagCategory', 'rest' : '\Tada\REST\TagCategoryREST', 'table' : 'tag_category' }

classes :
    Berthe-tasks-RESTBuilder :
        class : \Tada\RESTBuilder\TaskRESTBuilder
        call :
            setContainer : [ $container ]
            setResourceName : [ 'tasks' ]

    Berthe-tasks-FetcherBuilder:
        class : \Tada\FetcherBuilder\TaskFetcherBuilder

    Berthe-tags-FetcherBuilder:
        class : \Tada\FetcherBuilder\TagFetcherBuilder

    Berthe-tags-RESTBuilder :
        class : \Tada\RESTBuilder\TagRESTBuilder
        call :
            setContainer : [ $container ]
            setResourceName : [ 'tags' ]
            setTagCategoryService : [ @Berthe-tagcategories-Service ]

    Berthe-tagcategories-RESTBuilder :
        class : \Tada\RESTBuilder\TagCategoryRESTBuilder
        call :
            setContainer : [ $container ]
            setResourceName : [ 'tagcategories' ]

    Berthe-tags-Fetcher :
        class: \Tada\Model\TagFetcher

    Berthe-tasks-Manager :
        class : \Berthe\BaseManager
        call :
            addSaveHook[0] : [ @CreatedDateSaveHook ]
            addSaveHook[1] : [ @UpdatedDateSaveHook ]
            addSaveHook[2] : [ @NotificationSaveHook ]
            setValidator : [ @Berthe-tasks-Validator ]
            setStorage : [ @Berthe-tasks-Storage ]
            setVOFQCN : [ '\Tada\Model\Task' ]

    Berthe-tasks-Builder :
        class : \Tada\Model\TaskBuilder

    Berthe-tasks-Service :
        class: \Tada\Service\TaskService
        arguments: [ @Berthe-tasks-Manager, @Berthe-tasks-Builder ]
