routes:
    index:
        route:
            pattern: "/"
            methods: [ get ]
        dispatch:
            PyriteSessionFactory: { 'start': true }
            PyriteApplicationFactory:
                PhtmlRenderer[0] : [ main_layout.phtml ]
                PhtmlRenderer[1] : [ index/layout.phtml ]
                PhtmlRenderer[2] : [ index/head.phtml, header ]
                PhtmlRenderer[3] : [ index/template.phtml, template ]
                PhtmlRenderer[4] : [ index/task.phtml, task ]

                # ViewRenderer:
                #     success: /browser/twig/index/index.html.twig
                Executor: [ IndexController ]
    create:
        route:
            pattern: "/rest/tasks"
            methods: [ post ]
        dispatch:
            PyriteSessionFactory: { 'start': true }
            PyriteApplicationFactory:
                ApiLayer : []
                Executor: [ CreateTaskController ]

    update:
        route:
            pattern: "/rest/tasks/{id}"
            methods: [ put, patch ]
        dispatch:
            PyriteSessionFactory: { 'start': true }
            PyriteApplicationFactory:
                ApiLayer : []
                Executor: [ UpdateTaskController ]

include:
    - rest.yml
